export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED_DONE: "PROFILE_DATA_FETCHED_DONE",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  post: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED_DONE: "PROFILE_DATA_FETCHED_DONE",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    POST_LIKED: "POST_LIKED",
    POST_COMMENTED: "POST_COMMENTED",
  },
};
